-- LogWarden 0005 — authentication, roles and sessions

BEGIN;

-- ---------------------------------------------------------------------------
-- Role mapping: AD groups *and* individual accounts
-- ---------------------------------------------------------------------------

-- 0001 could only map groups. Mapping a single account matters in practice:
-- the one external auditor who needs read access does not justify a new AD
-- group, and waiting for one is how people end up sharing a login.
ALTER TABLE ldap_role_map RENAME COLUMN group_dn TO subject;

ALTER TABLE ldap_role_map ADD COLUMN subject_type text NOT NULL DEFAULT 'group'
    CHECK (subject_type IN ('group', 'user'));
ALTER TABLE ldap_role_map ADD COLUMN description text;
ALTER TABLE ldap_role_map ADD COLUMN enabled     boolean NOT NULL DEFAULT true;
ALTER TABLE ldap_role_map ADD COLUMN created_at  timestamptz NOT NULL DEFAULT now();
ALTER TABLE ldap_role_map ADD COLUMN created_by  text;

-- A group DN and an account name never collide, but the same subject must not
-- be listed twice. Case-insensitive because AD is.
ALTER TABLE ldap_role_map DROP CONSTRAINT IF EXISTS ldap_role_map_group_dn_key;
CREATE UNIQUE INDEX ldap_role_map_subject_idx ON ldap_role_map (subject_type, lower(subject));

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------

ALTER TABLE users ADD COLUMN password_changed_at  timestamptz;
ALTER TABLE users ADD COLUMN must_change_password boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN failed_logins        integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until         timestamptz;
ALTER TABLE users ADD COLUMN last_login_ip        inet;

-- Snapshot of the directory groups seen at the last login, and which mapping
-- entry granted the role. Without it the profile page can only state the
-- outcome, and "why do I not see the settings" has no answer.
ALTER TABLE users ADD COLUMN ldap_groups     jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE users ADD COLUMN role_matched_by text;

-- A local account with no usable password is a locked account, not a
-- passwordless one — the login path must never treat NULL as "no check".
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_local_needs_hash;
ALTER TABLE users ADD CONSTRAINT users_local_needs_hash
    CHECK (auth_provider <> 'local' OR password_hash IS NOT NULL);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------

-- Changing the authentication model invalidates what came before it; carrying
-- sessions across this migration would be the wrong kind of convenience.
DELETE FROM sessions;

-- The CSRF token lives with the session rather than in PHP's own session
-- storage, so there is exactly one session mechanism and revoking a row really
-- ends that session. Generated by the application rather than by a database
-- default, so pgcrypto is not a deployment prerequisite.
ALTER TABLE sessions ADD COLUMN csrf_token text NOT NULL;

-- Idle timeout renews on activity; the absolute one never does, so a stolen
-- session cannot be kept alive indefinitely by using it.
ALTER TABLE sessions ADD COLUMN absolute_expires_at timestamptz NOT NULL;

-- ---------------------------------------------------------------------------
-- Login attempts
-- ---------------------------------------------------------------------------

-- Separate from audit_log: this is queried on every login attempt for rate
-- limiting, and it holds attempts for accounts that do not exist.
CREATE TABLE login_attempts (
    id         bigserial PRIMARY KEY,
    ts         timestamptz NOT NULL DEFAULT now(),
    username   text NOT NULL,
    ip         inet,
    provider   text,
    success    boolean NOT NULL,
    reason     text,
    user_agent text
);

CREATE INDEX login_attempts_user_idx ON login_attempts (lower(username), ts DESC);
CREATE INDEX login_attempts_ip_idx   ON login_attempts (ip, ts DESC) WHERE ip IS NOT NULL;
CREATE INDEX login_attempts_ts_idx   ON login_attempts (ts DESC);

COMMIT;
